### ISSUE TITLE
Tool does not start without internet connection.

### ISSUE THREAD

**Issue by Crowley951** [callumhutchy/MultiConverter#10]
Tool does not start without internet connection.

when I start the tool without an internet connection it doesn't work.

It only works with an internet connection

I wanted to know if it is possible to use the tool offline as I work a lot locally offline, please help.

It would be nice if you make it possible Thank you

Otherwise good work keep it up.

**Comment by callumhutchy** [comment]
There was an old bit of code that was stalling your program if you ran it offline. This has been removed now.

**Comment by Crowley951** [comment]
> 
Thank you good job respect

Thanks
